#!/usr/bin/env python3

import sys
from glfsimage import GLFSImage

def mkfs():
	if len(sys.argv) != 2:
		print("Usage: glfs-mkfs <path>")
		return
	
	path = sys.argv[1]
	GLFSImage.create(path)
	print("Filesystem created successfully.")
	
if __name__ == '__main__':
	mkfs()